apiVersion: apps/v1
kind: Deployment
metadata:
  name: danuri-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: danuri-backend
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
