apiVersion: apps/v1
kind: Deployment
metadata:
  name: danuri-backend
  namespace: danuri
  labels:
    app: danuri-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: danuri-backend
  template:
    metadata:
      labels:
        app: danuri-backend
    spec:
      containers:
        - name: danuri-backend
          image: ghcr.io/danuri-team/danuri-backend:latest
          ports:
            - name: http
              containerPort: 8080
            - name: monitoring
              containerPort: 8081
          resources:
            limits:
              cpu: 400m
              memory: 1024Mi
            requests:
              cpu: 300m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          envFrom:
            - secretRef:
                name: danuri-backend
