apiVersion: apps/v1
kind: Deployment
metadata:
  name: danuri-backend
  namespace: danuri
  labels:
    app: danuri-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: danuri-backend
  template:
    metadata:
      labels:
        app: danuri-backend
    spec:
      containers:
        - name: danuri-backend
          image: ghcr.io/danuri-team/danuri-backend:latest
          ports:
            - name: http
              containerPort: 8080
            - name: monitoring
              containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: danuri-backend
